website/models.py
from . import db 
from flask_login import UserMixin
from sqlalchemy.sql import func

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique=True)
    username = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(150))
    notes = db.relationship('Notes')
    categories = db.relationship('Category')

class Category(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(150))
    user = db.Column(db.Integer, db.ForeignKey('user.id'))
    notes = db.relationship('Notes')

class Notes(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(150))
    note = db.Column(db.String(10000))
    category = db.Column(db.Integer, db.ForeignKey('category.id'))
    user = db.Column(db.Integer, db.ForeignKey('user.id'))
    pictures = db.relationship('Pictures')
    is_temp = db.Column(db.Integer)

class Pictures(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    key = db.Column(db.Integer)
    name = db.Column(db.String(150), unique=True)
    note = db.Column(db.Integer, db.ForeignKey('notes.id'))

website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask_login import LoginManager
from db_settings import *
import mysql.connector

db = SQLAlchemy()

def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'Ray Charles'
    app.config['SQLALCHEMY_DATABASE_URI'] = f"mysql+pymysql://{db_user}:@{db_host}/{db_name}"
    
    db.init_app(app)

    from .views import views
    from .auth import auth
    from .creator import creator

    app.register_blueprint(views, url_prefix="/")
    app.register_blueprint(auth, url_prefix="/")
    app.register_blueprint(creator, url_prefix="/")

    from .models import User

    create_database(app)

    create_guest()

    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))

    return app

def create_database(app):
    db.create_all(app=app)

def create_guest():
    mydb = mysql.connector.connect(
        host=db_host,
        user=db_user,
        passwd=db_password,
        database=db_name
    )
    my_cursor = mydb.cursor()
    
    my_cursor.execute(f"INSERT IGNORE INTO `user` (`id`, `email`, `username`, `password`) VALUES (1,'guest','guest','guest')")
    mydb.commit()
    my_cursor.execute(f"INSERT IGNORE INTO `category`(`id`, `name`, `user`) VALUES (1,'Empty',1)")
    mydb.commit()

    my_cursor.close()
    mydb.close()

website/auth.py
from urllib import request
from flask import Blueprint, render_template, request, flash, redirect, url_for, jsonify
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from flask_login import login_user, login_required, logout_user, current_user


auth = Blueprint('auth', __name__)

@auth.route('/welcome', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('views.home'))
    if request.method == 'POST':
        req = request.get_json()
        if req['request'] == 'login':
            # Jeigu svečias #
            if req['username'] == 'guest' and req['password'] == 'guest':
                user = User.query.filter_by(username='guest').first()
                login_user(user,remember=False)
                return jsonify({'response':1})
            user = User.query.filter_by(username=req['username']).first()
            if user:
                if check_password_hash(user.password, req['password']):
                    login_user(user,remember=True)
                    return jsonify({'response':1})
                else:
                    return jsonify({"response":'Vartotojas nerastas. Patikrinkite įvestus duomenis arba užsiregistruokite.'})
            else:
                return jsonify({'response':"Vartotojas nerastas."})
        elif req['request'] == 'register':
            # Tikrinam
            if req['email'] == '' or req['password'] == '' or req['username'] == '' or req['confirm'] == '':
                return jsonify({'response':'Užpildykite visus laukus'})
            check_email = User.query.filter_by(email = req['email']).first()
            if check_email:
                return jsonify({'response':'Elektroninio pašto adresas užimtas.'})
            check_username = User.query.filter_by(username = req['username']).first()
            if check_username:
                return jsonify({'response':"Vartotojo vardas užimtas."})
            if req['password'] != req['confirm']:
                return jsonify({'response':'Slaptažodžiai nesutampa.'})
            if len(req['password']) > 150:
                return jsonify({'response':'Per ilgas slaptažodis. Daugiausiai 150 simbolių.'})
            if len(req['username']) > 150:
                return jsonify({'response':'Per ilgas vartotojo vardas. Daugiausiai 150 simbolių.'})
            if req['username'].isascii() == False or req['username'].isalpha() == False:
                return jsonify({'response':'Vartotojo varde yra neleistinų simbolių.'})
            if not '@' in req['email'] or ' ' in req['email'] or not '.' in req['email']:
                return jsonify({'response':'Neteisingas el. pašto formatas.'})
                

            # Registruojam
            user = User(email=req['email'],
                username=req['username'],
                password = generate_password_hash(req['password'], method='sha256'))
            db.session.add(user)
            db.session.commit()
            login_user(user, remember=True)
            return jsonify({'response':1})       

    return render_template("login.html", user=current_user)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

website/views.py
from urllib import request
from flask import Flask, Blueprint, render_template, request, flash, jsonify, redirect, url_for, send_from_directory
from flask_login import login_required, current_user
from .models import User, Pictures, Notes, Category
from . import db
import os
from .functions import upload_img


views = Blueprint('views', __name__)

@views.route('/', methods=['GET', 'POST'])
@login_required
def home():
    if current_user.username == 'guest':
        return redirect(url_for('views.guest'))
    if len(current_user.notes) == 0:
        return redirect(url_for('creator.category'))
    return render_template("base.html", user=current_user)

@views.route('/categories', methods=['GET', 'POST'])
@login_required
def categories():
    if current_user.username == 'guest':
        return redirect(url_for('views.guest'))
    if request.method == 'GET':
        if 'cat' in request.values:
            category = Category.query.filter_by(id = request.values['cat']).first()
            if category.user == current_user.id:
                return render_template("categories.html", user = current_user, category = category)
            else:
                return redirect(url_for('creator.category'))
        else:
            return redirect(url_for('creator.category'))

@views.route('/note', methods=['GET', 'POST'])
@login_required
def notes():
    if current_user.username == 'guest':
        return redirect(url_for('views.guest'))
    if request.method == 'GET':
        if 'note' in request.values:
            note = Notes.query.filter_by(id=request.values['note']).first()
            category = Category.query.filter_by(id=note.category).first()
            if note.user == current_user.id:
                return render_template("notes.html", user=current_user, note=note, category=category)
    
    return redirect(url_for('views.home'))

@views.route('/guest', methods=['POST', 'GET'])
@login_required
def guest():
    if current_user.username != 'guest':
        return redirect(url_for('views.home'))
    note = 10

    if request.method == 'GET' and 'note' in request.values:
        if int(request.values['note']) < 10 and int(request.values['note']) >= 0: 
            return render_template("guest.html", user=current_user, note=request.values['note'])

    return render_template("guest.html", user=current_user, note=note)

@views.route('/images/<path:filename>')
@login_required
def get_image(filename):
    app = Flask(__name__)
    return send_from_directory(f"{app.root_path}/img",filename, as_attachment=True)

website/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>BETA</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css')}}">
</head>
<body>
    <div id="header">
        <div id="appname" onclick="location.replace('/')"><h1>BETA</h1><p>Jūsų užrašai</p></div>
        <div id="middle">
            {% if user.is_authenticated %}
                {% if user.username == 'guest' %}
                     Sėkmingo naudojimo!</br>
                     Jei patinka BETA - užsiregistruokite :)
                {% else %}
                    Sėkmingo naudojimo,</br>
                    {{ user.username }}
                {% endif %}
            {% else %}
            Sveiki atvykę!</br>
            Prisijunkite, kad galėtumėte tęsti
            {% endif %}
        </div>
        <div id="navbar">
            {% if user.is_authenticated == False %}
            <div class="nav-list"><a href="#">Prisijungti</a></div>
            <div class="nav-list"><a href="#">Registruotis</a></div>
            {% else %}
            {% if user.username == 'guest' %}
            <div class="nav-list"><a href='/guest'>Pagrindinis</a></div>
            {% else %}
            <div class="nav-list"><a href='/'>Pagrindinis</a></div>
            {% endif %}
            <div class="nav-list"><a href="/logout">Atsijungti</a></div>
            {% endif %}
        </div>
    </div>
    <div id="main">
        <div id="admin-nav">
            <h3>Užrašų kategorijos</h3>
            <ul style="overflow:auto;margin-bottom:auto">
                {% if user.is_authenticated and user.username != 'guest' %}
                    {% if user.categories %}
                        {% for x in user.categories %}
                            <a href="/categories?cat={{ x.id }}"><li>{{ x.name }}</li></a>
                        {% endfor %}
                    {% else %}
                        <a href="/category"><li>Sukurkite savo pirmą kategoriją</li></a>
                    {% endif %}
                {% elif user.username == 'guest' %}
                    <a href="#"><li>Kad galėtumėte naudotis kategorijomis - prisijunkite</li></a>
                {% else %}
                <a href="#"><li>Čia matysite savo užrašus</li></a>
                {% endif %}
            </ul>
            {% if user.username != 'guest' and user.is_authenticated and user.notes %}
            <div id="search">
                <h3>Paieška</h3>
                <div class="search-item">
                    <input placeholder="Kategorijos/užrašo pavadinimas" oninput="search(this)" onclick="search(this)">
                    <div class="search-list">
                        {% for x in user.categories %}
                            <div onclick="window.location.replace('/categories?cat={{x.id}}')" class="search-list-item" style="display:none"><b>K:</b> {{ x.name }}</div>
                        {% endfor %}
                        {% for x in user.notes %}
                            <div onclick="window.location.replace('/note?note={{x.id}}')" class="search-list-item" style="display:none"><b>U:</b> {{ x.name }}</div>
                        {% endfor %}
                    </div>
                    <script>
                        function search(element){
                            let searchList = document.getElementsByClassName('search-list')[0]
                            let searchItems = document.getElementsByClassName('search-list-item')
                            if(element.value != '') searchList.style.display = 'flex'
                            else return searchList.style.display = 'none'
                            for(let x=0;x<searchItems.length;x++){
                                if(searchItems[x].innerText.toLowerCase().indexOf(element.value.toLowerCase()) != -1){
                                    searchItems[x].style.display = 'block'
                                }
                                else{
                                    searchItems[x].style.display = 'none'
                                }
                            }
                        }
                        document.getElementsByTagName('body')[0].addEventListener("click", function(){
                            let searchList = document.getElementsByClassName('search-list')[0]
                            if(window.event.target != searchList) return searchList.style.display = 'none'
                        })
                    </script>
                </div>
            </div>
            {% endif %}
            <div id="admin-options">
                {% if user.is_authenticated and user.username != 'guest' %}
                <a href="/category"><div class="option">Kurti kategoriją/užrašą</div></a>
                <a href="/"><div class="option">Peržiūrėti užrašus</div></a>
                {% endif %}
            </div>
        </div>
        <div id="content">
            {% block content %}
            <h1>Jūsų užrašai, {{ user.username }}</h1>
            <div class="cat-wrapper">
                {% for x in user.notes %}
                <div class="categories">
                    <h1 onclick="location.replace('/note?note={{x.id}}')">{{x.name}}</h1>
                    <div class="notes-pictures">
                        {% if x.pictures %}
                            {% for y in x.pictures %}
                                <div onclick="document.getElementById('{{ y.id }}').showModal()"><img style="height:100%;width:100%" src="{{ url_for('views.get_image', filename=y.name) }}"></div>
                                <dialog class="picture" id="{{ y.id }}">
                                    <img src="{{ url_for('views.get_image', filename=y.name) }}">
                                    <div class="control">
                                        <div style="border-right: solid rgba(0, 0, 0, 0.356) 0.1px" onclick="document.getElementById('d{{y.id}}').click()"><a href="{{ url_for('views.get_image', filename=y.name) }}" id="d{{y.id}}" download hidden></a>Atsisiųsti nuotrauką</div>
                                        <div onclick="document.getElementById('{{ y.id }}').close()">Išjungti</div>
                                    </div>                            
                                </dialog>
                            {% endfor %}
                        {% if x.pictures |length < 4 %}
                            {% for a in range(0,4-x.pictures |length) %}
                            <div onclick="location.replace('/note?note={{ x.id }}')">+</div>
                            {% endfor %}
                        {% else %}
                            <div onclick="location.replace('/note?note={{ x.id }}')">+</div>
                        {% endif %}
                        {% else %}
                        <div>+</div>
                        <div>+</div>
                        <div>+</div>
                        <div>+</div>
                        {% endif %}
                    </div>
                    <p>{{x.note}}</p>
                </div>
            {% endfor %}
            <script>
                console.log('hello')
                function openDialog(dialog){
                    document.getElementsByClassName('picture')[parseInt(dialog)-1].showModal()
                }
            </script>
            </div>
        </div>
        {% endblock %}
        </div>
    </div>
</body>
</html>

website/templates/categories.html
{% extends "base.html" %}
{% block content %}
    {% if category %}
    <div class="settings">
        <div onclick="updateCategory(this, parseInt('{{category.id}}'))" style="border-right:1px solid rgba(0, 0, 0, 0.329)">Redaguoti</div>
        <div id="deleteCategory" onclick="deleteCategory(parseInt('{{category.id}}'))">Ištrinti</div>
    </div>
    <h1 class="cat-header">{{ category.name.upper() }}</h1>
    
    <div class="cat-wrapper" onlick="console.log(1+1)">
        <div class="categories">
            <h1>Pridėti užrašą</h1>
            <div class="notes-pictures" onclick="newNotePicture(this)">
                <div>+</div>
                <div>+</div>
                <div>+</div>
                <div>+</div>
                <input type="file" id="cat-picture" onchange="newNotePictureHandler(this)"  accept="image/png, image/jpeg" hidden>
            </div>
            <p>
                Pavadinimas:</br>
                <input id="note-name"></br>
                Užrašas:</br>
                <textarea rows="10" cols="30" id="create-note"></textarea></br>
                <button onclick="createNote('{{category.id}}')">Pridėti</button>
            </p>
        </div>
        <script src="{{ url_for('static', filename='category.js')}}"></script> 
    {% for x in category.notes %}
        <div class="categories">
            <h1 onclick="location.replace('/note?note={{x.id}}')">{{x.name}}</h1>
            <div class="notes-pictures" onclick="newNotePicture(this)">
                {% if x.pictures %}
                    {% for y in x.pictures %}
                        <div onclick="document.getElementById('{{ y.id }}').showModal()"><img style="height:100%;width:100%" src="{{ url_for('views.get_image', filename=y.name) }}"></div>
                        <dialog class="picture" id="{{ y.id }}">
                            <img src="{{ url_for('views.get_image', filename=y.name) }}">
                            <div class="control">
                                <div style="border-right: solid rgba(0, 0, 0, 0.356) 0.1px" onclick="document.getElementById('d{{y.id}}').click()"><a href="{{ url_for('views.get_image', filename=y.name) }}" id="d{{y.id}}" download hidden></a>Atsisiųsti nuotrauką</div>
                                <div onclick="document.getElementById('{{ y.id }}').close()">Išjungti</div>
                            </div>                            
                        </dialog>
                    {% endfor %}
                {% if x.pictures |length < 4 %}
                    {% for x in range(0,4-x.pictures |length) %}
                    <div>+</div>
                    {% endfor %}
                {% else %}
                    <div>+</div>
                {% endif %}
                {% else %}
                <div>+</div>
                <div>+</div>
                <div>+</div>
                <div>+</div>
                {% endif %}
                <input type="file" id="cat-picture" onchange="newNotePictureHandler(this, 1, parseInt('{{x.id}}'))"  accept="image/png, image/jpeg" hidden>
            </div>
            <p>{{x.note}}</p>
        </div>
    {% endfor %}
    <script>
        function openDialog(dialog){
            document.getElementsByClassName('picture')[parseInt(dialog)-1].showModal()
        }
    </script>
    </div>
    {% else %}
    <h1>Sukurkite naują užrašą</h1>
    <div class="cat-wrapper">
        <div class="categories">
            <h1>Pridėti užrašą</h1>
            <div class="notes-pictures">
                <div>+</div>
                <div>+</div>
                <div>+</div>
                <div>+</div>
            </div>
            <p>
                Pavadinimas:</br>
                <input></br>
                Užrašas:</br>
                <textarea rows="10" cols="30"></textarea></br>
                <button onclick="createNote()">Pridėti</button>
            </p>
        </div>
    </div>
    <script src="{{ url_for('static', filename='category.js')}}"></script> 
    {% endif %}
    <script src="{{ url_for('static', filename='pictureHandler.js') }}"></script>
    <script src="{{ url_for('static', filename='categoryHandler.js') }}"></script>
{% endblock %}

website/templates/create_category.html
{% extends "base.html" %}
{% block content %}
{% if user.username != 'guest' %}
{% if user.notes %}
<div class="login reg">
{% else %}
<div class="login">
{% endif %}
    <h1>Kurti kategoriją</h1>
    <form>
        <div id="cat-create-info">
            Pavadinimas:</br>
            <input id="cat-name" maxlength="30">
            {% if user.notes %}
            </br>
            Įtraukti užrašus:</br>
            <input id='note-item' list="notes-list">
                <datalist id="notes-list">
                    <script>
                        var optionElements = []
                        let tempCount
                    </script>
                    {% for x in user.notes %}
                        <!--<option value="{{ x.name }} (ID: {{ x.id }})">{{ x.name }}</option>!-->
                        <script>
                            optionElements.push([document.createElement('option'), "{{ x.name }} (ID: {{ x.id }})", parseInt("{{x.id}}")])
                            tempCount = parseInt(optionElements.length) - 1
                            optionElements[tempCount][0].value = optionElements[tempCount][1]
                            document.getElementById('notes-list').appendChild(optionElements[tempCount][0])
                        </script>
                    {% endfor %}
                </datalist>
            </input></br>
            <label id="add-note-item" onclick="addNoteToList()">Įtraukti</label>
            {% endif %}
        </div>
        {% if user.notes %}
        <div>
            Įtraukti užrašai:</br>
            <div class="small-list-wrapper"></div>
            <script>
                function addNoteToList(){
                    let inputValue = document.getElementById('note-item')
                    let optionsList = document.getElementsByTagName('option')

                    if(inputValue.value == '') return inputValue.style.borderColor = 'red'
                    else inputValue.style.borderColor = 'rgba(0, 64, 255, 0.5)'

                    let isInList = 0
                    let noteId = 0
                    for(let x=0;x<optionElements.length;x++){
                        if(optionElements[x].indexOf(inputValue.value) != -1) {
                            isInList = 1
                            noteId = optionElements[x][2]
                            break
                        }
                    }

                    if(isInList == 1) document.getElementsByClassName('small-list-wrapper')[0].innerHTML += `<div class='small-list-item' onclick='removeItem(this)' id=${noteId}>${inputValue.value}</div>`
                    else {
                        childs = document.getElementsByClassName('small-list-wrapper')[0].childNodes
                        if(childs.length != 0){
                            for(let x=0;x<childs.length;x++){
                                if(childs[x].innerHTML.indexOf('<i style="color:red;font-size:0.5rem">NAUJAS</i>') != -1){
                                    return alert('Galima pridėti tik vieną naują užrašą.')
                                }
                            }
                        }
                        document.getElementsByClassName('small-list-wrapper')[0].innerHTML += `<div class='small-list-item' onclick='this.remove()'><i style='color:red;font-size:0.5rem'>NAUJAS</i> ${inputValue.value}</div>`
                    }
                    for(let x=0;x<optionsList.length;x++){
                        if(optionsList[x].value == inputValue.value){
                            document.getElementById('notes-list').removeChild(optionsList[x])
                            break
                        }
                    }
                    inputValue.value = ''
                }
                function removeItem(item){
                    for(let x=0;x<optionElements.length;x++){
                        if(optionElements[x][2] == item.id){
                            document.getElementById('notes-list').appendChild(optionElements[x][0])
                            break
                        }
                    }
                    item.remove()
                }
            </script>
        </div>
        <script>
            document.getElementsByClassName('login reg')[0].addEventListener('mouseover',firstCalc)
            function firstCalc(){
                document.getElementsByClassName('small-list-wrapper')[0].style.height = `${document.getElementById('cat-create-info').offsetHeight}px`
                document.getElementsByClassName('small-list-wrapper')[0].style.width = `${document.getElementById('cat-create-info').offsetWidth}px`
                this.removeEventListener('mouseover', firstCalc)
            }
        </script>
        {% endif %}
    </form>
    {% if user.notes %}
    <div class="login-btn" onclick="createCategory(0)">Sukurti</div>
    {% else %}
    <div class="login-btn" onclick="createCategory(1)">Sukurti</div>
    {% endif %}
</div>
<div class="login reg">
    <h1>Kurti užrašą</h1>
    <form>
        <div>
            Pavadinimas:</br>
            <input id="note-name"></br></br>
            Pridėti paveiksliuką <i id="imgCount">(0)</i>:
            <label for="cat-picture">Pridėti</label>
            <input type="file" accept="image/png, image/jpeg" style="border:none" id="cat-picture" multiple>
        </div>
        <div>
            Tekstas:</br>
            <textarea id="create-note"></textarea>
        </div>
    </form>
    <div class="login-btn" onclick="createNote()">Sukurti</div>
</div>
<script src="{{ url_for('static', filename='category.js')}}"></script> 
<script>
document.getElementById('cat-picture').addEventListener('change', function(){
    document.getElementById('imgCount').innerText = document.getElementById('cat-picture').files.length
    //alert(document.getElementById('cat-picture').files[0].size)
})
</script>
{% endif %}
{% endblock %}

website/templates/guest.html
{% extends "base.html" %}
{% block content %}
{% if note|int == 10 %}
<h1>Jūsų temos</h1></br>
<i>Visi duomenys saugomi Jūsų kompiuteryje, tad ištrynus naršymo istoriją - jie dings.</br>
    Svečio vartotojas gali pridėti daugiausiai 10 įrašų. Jei norite pridėti daugiau - prisijunkite.
</i>
<div class="cat-wrapper">
    <div class="categories">
        <h1>Pridėti užrašą</h1>
        <div class="notes-pictures" onclick="newNotePicture(this)">
            <div onclick="location.replace('/logout')">Kad galėtumėte pridėti nutoraukas - prisijunkite</div>
        </div>
        <p>
            Pavadinimas:</br>
            <input id="note-name"></br>
            Užrašas:</br>
            <textarea rows="10" cols="30" id="create-note"></textarea></br>
            <button onclick="createNote()">Pridėti</button>
        </p>
    </div>
</div>
<script src="{{ url_for('static', filename='guest.js') }}"></script>
<script>displayNotes()</script>
{% elif note|int >= 0 and note|int < 10 %}
<div class="note-wrapper">
    <h1 id="name"></h1>
    <div class="note-info">
        Kategorija: 
        <select disabled>
            <option>Svečio režime kategorijos nepasiekiamos.</option>
        </select>
    </div>
    <div class="notes-pictures" style="height:20vh;width:100%">
        <div style="height:100%;width:100%" onclick="location.replace('/logout')">Kad galėtumėte pridėti nutoraukas - prisijunkite</div>
    </div>
    <p onclick="invertNoteColors(this)" id="note"></p>
    <div class="settings">
        <div id="edit" onclick="editMode(parseInt('{{note}}'))" style="border-right:1px solid rgba(0, 0, 0, 0.329)">Redaguoti</div>
        <div id="delete" onclick="deleteNote(parseInt('{{ note }}'))">Ištrinti</div>
    </div>
</div>
<script src="{{ url_for('static', filename='guest.js') }}"></script>
<script>noteInfo(parseInt('{{note}}'))</script>
{% endif %}
{% endblock %}

website/templates/notes.html
{% extends "base.html" %}
{% block content %}
<div class="note-wrapper">
    <h1>{{ note.name }}</h1>
    <div class="note-info">
        Kategorija: 
        <select onchange="changeCategory(this, '{{note.id}}')">
            <option value="{{ category.id }}">{{ category.name }}</option>
            {% for x in user.categories %}
                {% if x.name != category.name %}
                    <option value="{{ x.id }}">{{ x.name }}</option>
                {% endif %}
            {% endfor %}
        </select>
    </div>
    <div class="notes-pictures" style="height:20vh;overflow-x:auto" onclick="newNotePicture(this)">
        {% for y in note.pictures %}
            <div style="width:calc(100%/7)" onclick="document.getElementById('{{ y.id }}').showModal()"><img style="max-width:100%;max-height:100%" src="{{ url_for('views.get_image', filename=y.name) }}"></div>
            <dialog class="picture" id="{{ y.id }}">
                <img src="{{ url_for('views.get_image', filename=y.name) }}">
                <div class="control">
                    <div style="border-right: solid rgba(0, 0, 0, 0.356) 0.1px" onclick="document.getElementById('d{{y.id}}').click()"><a href="{{ url_for('views.get_image', filename=y.name) }}" id="d{{y.id}}" download hidden></a>Atsisiųsti nuotrauką</div>
                    <div onclick="document.getElementById('{{ y.id }}').close()">Išjungti</div>
                </div>                            
            </dialog>
        {% endfor %}
        {% if note.pictures |length < 7 %}
            {% for x in range(0,7-note.pictures |length) %}
                <div style="width:calc(100%/7)">+</div>
            {% endfor %}
        {% endif %}
        <input type="file" id="cat-picture" onchange="newNotePictureHandler(this, 1, parseInt('{{note.id}}'))"  accept="image/png, image/jpeg" hidden>
    </div>
    <p onclick="invertNoteColors(this)">&nbsp;&nbsp;&nbsp;&nbsp;{{ note.note }}</p>
    <dialog id="note">&nbsp;&nbsp;&nbsp;&nbsp;{{ note.note }}</dialog>
    <div class="settings">
        <div onclick="changeNote(this, '{{note.id}}')" style="border-right:1px solid rgba(0, 0, 0, 0.329)">Redaguoti</div>
        <div onclick="deleteNote(this, '{{note.id}}')">Ištrinti</div>
    </div>
    <script src="{{ url_for('static', filename='category.js')}}"></script> 
    <script src="{{ url_for('static', filename='pictureHandler.js') }}"></script>
    <script src="{{ url_for('static', filename='notesHandler.js') }}"></script>
</div>
{% endblock %}